# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo
pod 'VWO', '~>2.0.0-rc.3'

end

